import { Boxes, Building2, CalendarClock, CircleHelp, ClipboardList, LayoutDashboard, ListChecks, MapPinned, PackageCheck, Route, ShieldAlert, Truck, Warehouse, Wifi, History, Plus, Package, Flag, Layers3 } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type WorkspaceId = 'dispatcher' | 'loader' | 'driver' | 'store';
export interface NavigationItem { path: string; label: string; icon: LucideIcon }
export interface Workspace { id: WorkspaceId; name: string; subtitle: string; title: string; description: string; icon: LucideIcon; navigation: NavigationItem[]; scope: { title: string; description: string; icon: LucideIcon }[] }
export const workspaces: Workspace[] = [
  { id: 'dispatcher', name: 'Dispatcher', subtitle: 'Operations workspace', title: 'A clearer view of every delivery.', description: 'One connected workspace for the decisions that move Waypoint forward.', icon: LayoutDashboard,
    navigation: [{ path: '', label: 'Overview', icon: LayoutDashboard }, { path: 'orders', label: 'Orders', icon: ClipboardList }, { path: 'planning', label: 'Planning', icon: Route }, { path: 'fleet', label: 'Fleet', icon: Truck }, { path: 'deliveries', label: 'Deliveries', icon: PackageCheck }, { path: 'deferrals', label: 'Deferrals', icon: History }, { path: 'exceptions', label: 'Exceptions', icon: ShieldAlert }, { path: 'capacity', label: 'Future capacity', icon: CalendarClock }],
    scope: [{ title: 'Plan with context', description: 'A reserved home for orders, fleet constraints and explainable allocation.', icon: Route }, { title: 'Keep the handoff clear', description: 'A consistent path from the planning office to the loading dock.', icon: Warehouse }, { title: 'Follow the delivery', description: 'A place for delivery evidence, exceptions and store receipt.', icon: MapPinned }] },
  { id: 'loader', name: 'Loader', subtitle: 'Warehouse workspace', title: 'The right load. A clear handoff.', description: 'A focused workspace for the warehouse dock, designed around the next action.', icon: Warehouse,
    navigation: [{ path: '', label: 'Assigned loads', icon: Boxes }, { path: 'active', label: 'Active load', icon: ListChecks }, { path: 'issues', label: 'Loading issues', icon: Flag }],
    scope: [{ title: 'Assigned loads', description: 'Your current loading jobs will appear here in a later phase.', icon: Boxes }, { title: 'Loading checklist', description: 'Stop sequence and loading checks will share one focused view.', icon: ListChecks }, { title: 'Clear exceptions', description: 'Missing, damaged and short goods will have an explicit reporting flow.', icon: Flag }] },
  { id: 'driver', name: 'Driver', subtitle: 'On the road', title: 'Your next stop, made clear.', description: 'A phone-first workspace for use when safely stopped.', icon: Truck,
    navigation: [{ path: '', label: 'Today', icon: CalendarClock }, { path: 'trip', label: 'Active trip', icon: Route }, { path: 'sync', label: 'Sync', icon: Wifi }],
    scope: [{ title: 'Today’s trips', description: 'Assigned trips and stop details will be added in the delivery phase.', icon: Route }, { title: 'Delivery evidence', description: 'Arrival, outcomes and proof of delivery are planned for a later phase.', icon: PackageCheck }, { title: 'Work that stays with you', description: 'Offline storage and safe synchronization have not been implemented yet.', icon: Wifi }] },
  { id: 'store', name: 'Store Manager', subtitle: 'Outlet workspace', title: 'Know what’s coming next.', description: 'A simple connection between your outlet and the delivery team.', icon: Building2,
    navigation: [{ path: '', label: 'Overview', icon: LayoutDashboard }, { path: 'orders', label: 'Orders', icon: ClipboardList }, { path: 'create', label: 'Create order', icon: Plus }, { path: 'issues', label: 'Delivery issues', icon: CircleHelp }],
    scope: [{ title: 'Order with confidence', description: 'Order capture and clear confirmation will be introduced in the order phase.', icon: Package }, { title: 'Understand the arrival', description: 'Scheduling and deferral notices will keep expectations explicit.', icon: CalendarClock }, { title: 'Close the loop', description: 'Receipt confirmation and issue reporting will connect the store to operations.', icon: Layers3 }] },
];
