import { AlertTriangle, CheckCircle2, CircleAlert, Info, Search, Truck } from 'lucide-react';
import { ActionButton, ActionLink, Card, IconBubble, KeyRows, ModalPage, OperationsShell, PageHeading, RadioCard, ResultCard, StatusChip, Timeline } from './ui';

const queue = [
  ['ORD0096515','OUT008','Fresh · Chilled','33','253.7 kg','05:00–07:30','2 days in a row'], ['ORD0096650','OUT008','Fresh · Chilled','31','232.7 kg','05:00–07:30','2 days in a row'], ['ORD0096518','OUT010','Fresh · Chilled','40','264.5 kg','05:00–07:30','2 days in a row'], ['ORD0096654','OUT010','Fresh · Chilled','40','293.5 kg','05:00–07:30','2 days in a row'], ['ORD0096520','OUT011','Fresh · Chilled','36','249.9 kg','03:00–08:00','2 days in a row'], ['ORD0096656','OUT011','Fresh · Chilled','27','198.2 kg','03:00–08:00','2 days in a row'], ['ORD0096522','OUT012','Fresh · Chilled','34','263.3 kg','05:30–08:00','2 days in a row'], ['ORD0096658','OUT012','Fresh · Chilled','45','292.1 kg','05:30–08:00','2 days in a row'], ['ORD0096647','OUT006','Fresh · Chilled','66','534.0 kg','03:00–08:00','Rolled over'], ['ORD0096652','OUT009','Fresh · Chilled','43','299.2 kg','04:00–07:45','Rolled over'], ['ORD0096815','OUT031','Fresh · Chilled','210','1,183.9 kg','03:00–08:00','Unusual quantity'], ['ORD0096797','OUT010','Fresh · Dry','45','359.0 kg','05:00–07:30','New'], ['ORD0096821','OUT035','Style · Ambient','40','657.5 kg','Mall 10:30–12:30','Mall dock'],
];

const vehicles = [
  ['VEH006','Reefer truck · 6,840 kg · 33.4 m³','Trip 1 · Fresh chilled · departs 04:52','OUT008 · OUT008 · OUT010 · OUT009 · OUT011 · OUT011 · OUT012','2496 / 6840 kg','13.3 / 33.4 m³','245 / 270 min','Window missed ×2'],
  ['VEH007','Reefer truck · 3,610 kg · 19.4 m³','Trip 1 · Fresh chilled · Puttalam · departs 02:00','OUT073 · OUT075','599 / 3610 kg','3.1 / 19.4 m³','276 / 270 min','Over time budget'],
  ['VEH005','Reefer truck · 6,840 kg · 33.4 m³','Trip 1 · Fresh chilled · departs 04:14','OUT010 · OUT013 · OUT005 · OUT006 · OUT007 · OUT012 · OUT014','3090 / 6840 kg','16.3 / 33.4 m³','180 / 270 min','All checks pass'],
  ['VEH012','Ambient truck · 4,200 kg · 24 m³','Trip 1 · Fresh · departs 04:08','OUT008 · OUT010 · OUT009 · OUT011 · OUT014','1605 / 4200 kg','8.6 / 24.0 m³','133 / 270 min','All checks pass'],
  ['VEH008','Ambient truck · 3,800 kg · 22 m³','Trip 1 · Puttalam · departs 02:00','OUT073 · OUT074 · OUT075 · OUT035 · OUT036','785 / 3800 kg','4.7 / 22.0 m³','252 / 270 min','Trip 2 at 92% volume'],
];

function StatCards({ fixed = false }: { fixed?: boolean }) {
  const values = fixed ? [['89 / 90','Orders planned','1 deferred with reason'],['19','Vehicles','VEH036 added'],['22','Trips','2 vehicles run 2 trips'],['0','Hard-rule failures','Ready to publish']] : [['90 / 90','Orders planned','Protected outlets placed first'],['18','Vehicles','20 idle at depot'],['21','Trips','2 vehicles run 2 trips'],['2','Hard-rule failures','Publishing is blocked']];
  return <div className="ops-stats">{values.map(([value,label,detail]) => <Card key={label}><strong>{value}</strong><span>{label}</span><small>{detail}</small></Card>)}</div>;
}

function VehicleLane({ row, fixed = false }: { row: string[]; fixed?: boolean }) {
  const [id,type,trip,stops,weight,volume,time,status] = row;
  const warning = !fixed && (status.includes('missed') || status.includes('Over'));
  return <Card className={`vehicle-lane ${warning ? 'rule-fail' : ''}`}><div className="vehicle-head"><div><strong>{id}</strong><small>{type}</small></div><div><span>{trip}</span><div className="stop-chips">{stops.split(' · ').map((stop) => <i key={stop}>{stop}</i>)}</div></div></div><StatusChip tone={warning ? 'danger' : status.includes('92') ? 'warning' : 'success'}>{fixed && warning ? 'All checks pass' : status}</StatusChip><div className="capacity-grid">{[['Weight',weight],['Volume',volume],['Trip time',time]].map(([label,value], index) => <div key={label}><small>{label}</small><strong>{value}</strong><span><i className={index === 2 && warning ? 'danger' : ''} style={{width: `${index === 2 && warning ? 100 : 56}%`}} /></span></div>)}</div></Card>;
}

function ConstraintCheck({ fixed = false }: { fixed?: boolean }) {
  const rules = [['Weight and volume','Every trip is within its vehicle’s limits.'],['Temperature','All 38 chilled orders are on reefer vehicles.'],['Van-only and mall dock','OUT001–OUT003 on van VEH038; OUT035–OUT036 in the mall slot.'],['Delivery windows',fixed ? 'OUT012 now served by VEH036 at 05:30.' : 'VEH006 reaches OUT012 after the window closes.'],['Trip-time budget',fixed ? 'VEH007 now 230 of 270 min.' : 'VEH007 needs 276 of 270 min for its Puttalam trip.'],['Fuel quota','All vehicles within their weekly quota.'],['Depot, brand and district','Every order matches its vehicle’s depot and trip type.'],['Whole orders','No order is split across vehicles.'],['Trips per vehicle','Maximum 2 trips.']];
  return <Card className="constraint-card"><div className="section-title-row"><h2>Constraint check</h2><StatusChip tone={fixed ? 'success' : 'danger'}>{fixed ? 'All pass' : '2 failures'}</StatusChip></div>{rules.map(([title,text],index) => <div className="rule-row" key={title}><span className={fixed || ![3,4].includes(index) ? 'pass' : 'fail'}>{fixed || ![3,4].includes(index) ? '✓' : '!'}</span><div><strong>{title}</strong><small>{text}</small>{!fixed && index === 3 && <ActionLink kind="secondary" to="/dispatcher/dp-o1">Move OUT012 to VEH036</ActionLink>}{!fixed && index === 4 && <ActionLink kind="secondary" to="/dispatcher/dp-o2">Review options</ActionLink>}</div></div>)}<ActionLink className="full" kind={fixed ? 'primary' : 'secondary'} to={fixed ? '/dispatcher/dp04' : '/dispatcher/dp02'}>{fixed ? 'Review and publish' : 'Publishing is blocked'}</ActionLink></Card>;
}

export function OrderQueue() {
  return <OperationsShell role="Dispatcher" active="plan" badge="Queue closed"><PageHeading title="Order queue · Wed 25 Mar" subtitle="Peliyagoda · Queue closed at 16:00 on Tue 24 Mar · all confirmed orders in one place" /><div className="queue-stats">{[['90','Orders','87 Fresh · 3 Style'],['80','New','Submitted before 16:00'],['10','Rolled over','Deferred earlier · priority'],['4','Protected outlets','Deferred 2 days in a row'],['1','Unusual quantity','1.6× the outlet’s usual']].map(([v,l,d]) => <Card key={l}><strong>{v}</strong><span>{l}</span><small>{d}</small></Card>)}</div><Card className="table-card"><div className="filter-row"><button className="active">All</button>{['Rolled over','Protected','Chilled','Style & Tech','Flags'].map(x=><button key={x}>{x}</button>)}</div><div className="data-table queue-table"><div className="table-head"><span>Order</span><span>Outlet</span><span>Brand · temp</span><span>Units</span><span>Weight</span><span>Window</span><span>Flags</span></div>{queue.map(row => <div className="table-row" key={row[0]}>{row.slice(0,6).map(cell=><span key={cell}>{cell}</span>)}<StatusChip tone={row[6].includes('2 days') ? 'danger' : 'warning'}>{row[6]}</StatusChip></div>)}</div><div className="table-footer"><span>Showing 13 of 90 orders · priority first</span><ActionLink to="/dispatcher/dp02">Generate assisted plan</ActionLink></div></Card></OperationsShell>;
}

function PlanScreen({ fixed = false }: { fixed?: boolean }) {
  return <OperationsShell role="Dispatcher" active="plan"><PageHeading title="Plan · Wed 25 Mar 2026" subtitle={fixed ? 'Assisted plan with your changes · re-checked 16:18' : 'Assisted plan generated at 16:12 · review, fix and approve before publishing'} /><StatCards fixed={fixed} /><div className="plan-layout"><div><div className="section-title-row"><h2>Vehicles</h2><div><StatusChip>Stop</StatusChip> <StatusChip tone="warning">Rolled over</StatusChip> <StatusChip tone="danger">Breaks a rule</StatusChip></div></div>{vehicles.map(row => <VehicleLane row={row} fixed={fixed} key={row[0]} />)}<Card className="vehicle-more"><strong>13 more vehicles · 15 trips · 61 orders</strong><span>All checks pass</span><button>Show all</button></Card></div><div><ConstraintCheck fixed={fixed} />{fixed ? <div className="info-banner"><Info /><div><strong>1 order deferred with a reason</strong><p>ORD0096862 (OUT075, chilled) → Thu 26 Mar. Reason: Other — trip-time budget.</p></div></div> : <div className="warning-banner"><AlertTriangle /><div><strong>4 protected outlets</strong><p>OUT008, OUT010, OUT011 and OUT012 were deferred 2 days in a row.</p></div></div>}</div></div></OperationsShell>;
}
export const DraftPlan = () => <PlanScreen />;
export const FixedPlan = () => <PlanScreen fixed />;

export function MoveOutletDialog() {
  return <ModalPage title="Move OUT012 to VEH036" description="Fix 1 of 2 · delivery windows"><p>ORD0096522 and ORD0096658 (OUT012 · 555.4 kg · 2.951 m³) move from VEH006 to the idle reefer van VEH036. VEH036 arrives at 05:30; VEH006 now finishes at 07:56, inside every window.</p><div className="modal-actions"><ActionLink kind="secondary" to="/dispatcher/dp02">Cancel</ActionLink><ActionLink to="/dispatcher/dp-o2">Move and continue</ActionLink></div></ModalPage>;
}

export function DeferralDecisionDialog() {
  return <ModalPage title="Fix 2 of 2 · VEH007 trip-time budget" description="The Puttalam trip needs 276 of 270 minutes. Choose how to bring it within the Fresh limit."><Card className="modal-summary"><KeyRows rows={[["Order",'ORD0096862 · OUT075'],["Load",'Fresh chilled · 30 units · 199.9 kg'],["Service history",<StatusChip tone="success">No deferrals in 14 days</StatusChip>]]} /></Card><div className="radio-stack"><RadioCard title="Defer ORD0096862 to Thu 26 Mar" description="VEH007 then needs 230 of 270 min. The order keeps priority for tomorrow." checked /><RadioCard title="Move to another reefer vehicle" description="No reefer vehicle can reach Puttalam within its budget today." /></div><span className="field-label">Reason (required)</span><div className="filter-row"><button>Capacity full</button><button>Temperature vehicle unavailable</button><button>Delivery window conflict</button><button>Fuel quota</button><button>Access restriction</button><button className="active">Other</button></div><label className="field-label">Note (required for Other)<textarea defaultValue="Puttalam trip exceeds the 270-min Fresh budget; second stop moved to Thu 26 Mar." /></label><div className="modal-actions"><ActionLink kind="secondary" to="/dispatcher/dp02">Cancel</ActionLink><ActionLink to="/dispatcher/dp03">Defer with reason</ActionLink></div></ModalPage>;
}

export function PublishReview() {
  return <OperationsShell role="Dispatcher" active="plan"><PageHeading backTo="/dispatcher/dp03" backLabel="Back to plan" title="Publish plan v1" subtitle="Wed 25 Mar 2026 · Peliyagoda" /><div className="two-column"><Card><h2>Summary</h2><KeyRows rows={[["Orders planned",'89 of 90'],["Deferred",'1 · ORD0096862 → Thu 26 Mar (reason recorded)'],["Vehicles · trips",'19 · 22'],["Protected outlets",'All 4 served'],["Hard rules",<StatusChip tone="success">All pass</StatusChip>],["Warnings",<StatusChip tone="warning">VEH008 trip 2 at 92% volume</StatusChip>]]} /></Card><Card><h2>Who is affected</h2>{[['Loaders · Peliyagoda','22 trips appear in the loading queue in stop-reverse order.'],['Drivers','19 vehicles get their assigned trip and stop sequence.'],['Store managers','52 outlets see their planned window.']].map(([a,b])=><div className="audience-row" key={a}><IconBubble icon={Truck}/><div><strong>{a}</strong><small>{b}</small></div></div>)}</Card></div><div className="inline-actions publish-actions"><ActionLink to="/dispatcher/dp05">Publish v1</ActionLink><ActionLink kind="secondary" to="/dispatcher/dp03">Back to plan</ActionLink></div></OperationsShell>;
}

export function PublishedPlan() {
  return <OperationsShell role="Dispatcher" active="plan" badge="Published v1"><div className="center-result"><ResultCard title="Plan v1 published" description="Loaders, drivers and stores have received their part of the plan."><KeyRows rows={[["Version",'v1'],["Published",'Tue 24 Mar 2026 · 16:22'],["For",'Wed 25 Mar · Peliyagoda'],["Sent to",'22 loader trips · 19 drivers · 52 outlets'],["Audit entry",'Plan published by Dispatcher']]} /><div className="inline-actions"><ActionLink to="/dispatcher/dp08">Open Live Board</ActionLink><ActionLink kind="secondary" to="/dispatcher/dp03">Back to plan</ActionLink></div></ResultCard></div></OperationsShell>;
}

const affected = [['ORD0096826','OUT041','52','336.6 kg','05:00–07:30'],['ORD0096830','OUT043','34','232.1 kg','05:00–07:30'],['ORD0096833','OUT046','35','201.2 kg','05:00–07:30'],['ORD0096824','OUT040','103','696.2 kg','03:00–08:00'],['ORD0096828','OUT042','115','1,024.0 kg','03:00–08:00'],['ORD0096831','OUT044','45','316.9 kg','03:00–08:00'],['ORD0096832','OUT045','33','267.3 kg','03:00–08:00']];

export function VehicleUnavailable() {
  return <OperationsShell role="Dispatcher" active="plan" badge="Published v1"><PageHeading title="Plan v1 needs a change" subtitle="Wed 25 Mar 2026 · 03:05 · before loading starts" /><div className="danger-banner"><CircleAlert /><div><strong>VEH025 reported unavailable — breakdown at the depot</strong><p>Trip 1 (Kalutara, 7 Fresh orders, departs 03:53) cannot run. Loading for this trip is on hold.</p></div></div><div className="plan-change-layout"><div><Card><div className="section-title-row"><h2>Affected orders</h2><StatusChip tone="danger">7 orders · 3,074.3 kg · 17.0 m³</StatusChip></div><div className="data-table affected-table"><div className="table-head"><span>Order</span><span>Outlet</span><span>Units</span><span>Weight</span><span>Window</span></div>{affected.map(row=><div className="table-row" key={row[0]}>{row.map(x=><span key={x}>{x}</span>)}</div>)}</div></Card><Card><h2>Options</h2><div className="radio-stack"><RadioCard title="Swap to VEH009 (recommended)" description="Idle ambient truck at Peliyagoda. Same route and stop order, no deferrals." checked /><RadioCard title="Split across VEH013 and VEH021" description="Two idle trucks. Needs a second loader bay and a new stop order." /><RadioCard title="Defer the 7 orders" description="Not recommended: capacity is available at the depot today." /></div></Card></div><Card className="summary-card"><h2>VEH009 check</h2><p>Ambient truck · 5,800 kg · 30 m³ · idle</p><KeyRows rows={[["Weight",'3047 / 5800 kg'],["Volume",'17.0 / 30.0 m³'],["Trip time",'254 / 270 min'],["Fuel quota",'Within VEH009’s weekly quota'],["Windows",'All 7 stops arrive inside their windows']]} /><ActionLink className="full" to="/dispatcher/dp07">Apply swap and re-check</ActionLink></Card></div></OperationsShell>;
}

export function PublishV2() {
  return <OperationsShell role="Dispatcher" active="plan"><PageHeading title="Publish plan v2" subtitle="Change from v1 · re-checked 03:08" /><div className="two-column"><Card><h2>What changed</h2><KeyRows rows={[["Vehicle",'VEH025 → VEH009'],["Trip",'Trip 1 · Kalutara · 7 orders'],["Stop order",'Unchanged'],["Deferrals",'None'],["Hard rules",<StatusChip tone="success">All pass</StatusChip>]]} /></Card><Card><h2>Who is affected</h2>{[['Loaders · Peliyagoda','The Kalutara trip reopens for verification with a “Plan changed” alert.'],['Drivers','VEH025’s driver is reassigned to VEH009. Stop list is unchanged.'],['Store managers','No change to delivery windows for OUT040–OUT046.']].map(([a,b])=><div className="audience-row" key={a}><IconBubble icon={Truck}/><div><strong>{a}</strong><small>{b}</small></div></div>)}</Card></div><div className="inline-actions publish-actions"><ActionLink to="/dispatcher/dp08">Publish v2</ActionLink><ActionLink kind="secondary" to="/dispatcher/dp06">Cancel</ActionLink></div></OperationsShell>;
}

const liveRows = [['VEH012','Colombo · Fresh','3 / 5','OUT011 · ETA 05:43','03:00–08:00','Back online · syncing'],['VEH005','Colombo · chilled','3 / 7','OUT006 · ETA 05:47','03:00–08:00','On time'],['VEH006','Colombo · chilled','2 / 8','OUT010 · ETA 06:01','05:00–07:30','On time'],['VEH036','Colombo · chilled','1 / 2','OUT012 · ETA 05:45','05:30–08:00','On time'],['VEH009','Kalutara · Fresh (v2)','2 / 7','OUT046 · ETA 05:59','05:00–07:30','On time'],['VEH038','Colombo · van-only','2 / 3','OUT002 · ETA 06:03','05:30–08:00','On time'],['VEH008','Puttalam · Fresh','2 / 3','OUT075 · ETA 05:57','03:00–08:00','On time'],['VEH007','Puttalam · chilled','1 / 1','Returning to depot','—','Trip complete']];
export function LiveBoard() {
  return <OperationsShell role="Dispatcher" active="board" badge="Published v2"><PageHeading title="Live Board" subtitle="Wed 25 Mar 2026 · 05:40 · Plan v2" /><div className="ops-stats">{[['22','Trips today','20 on the road now'],['27 / 89','Stops done','By planned time'],['0','Late','All inside windows'],['1','Offline','VEH012 · syncing now']].map(([v,l,d])=><Card key={l}><strong>{v}</strong><span>{l}</span><small>{d}</small></Card>)}</div><Card className="table-card"><h2>Route tracking <small>ETA uses the plan, updated by driver events.</small></h2><div className="data-table live-table"><div className="table-head"><span>Vehicle</span><span>Route</span><span>Progress</span><span>Next stop</span><span>Window</span><span>Status</span></div>{liveRows.map(row=><div className="table-row" key={row[0]}>{row.slice(0,5).map((x,i)=><span key={x}>{i===2 ? <><i className="mini-progress"><b style={{width:`${Number(x[0])*20}%`}} /></i>{x}</> : x}</span>)}<StatusChip tone={row[5].includes('On time') ? 'success' : 'warning'}>{row[5]}</StatusChip></div>)}</div></Card><div className="warning-banner"><AlertTriangle/><div><strong>VEH012 back online at 05:39 — 1 record needs review</strong><p>Offline 05:10–05:39. The driver kept working; OUT009’s delivery is waiting for the driver’s review before it syncs.</p></div></div></OperationsShell>;
}

export function NeedsAttention() {
  return <OperationsShell role="Dispatcher" active="attention" badge="Queue closed"><PageHeading title="Needs Attention" subtitle="Items that need a decision. Critical items use icon, text and coral — never colour alone." /><div className="attention-list"><div className="attention-case critical"><IconBubble icon={CircleAlert} tone="danger"/><div><StatusChip tone="danger">Critical</StatusChip><strong>Consecutive deferrals at 4 outlets</strong><p>OUT008, OUT010, OUT011 and OUT012 were deferred on Mon 23 and Tue 24 Mar.</p></div><ActionLink kind="secondary" to="/dispatcher/dp12">View deferral log</ActionLink></div><div className="attention-case"><IconBubble icon={AlertTriangle} tone="warning"/><div><StatusChip tone="warning">Warning</StatusChip><strong>Issue ISS-0417 · OUT010 · 2 cartons of Cream crackers short</strong><p>Reported by the store at 15:45 on ORD0096653. The loader flagged the same shortfall at 03:58.</p></div><ActionLink to="/dispatcher/dp10">Open case</ActionLink></div><div className="attention-case"><IconBubble icon={AlertTriangle} tone="warning"/><div><StatusChip tone="warning">Warning</StatusChip><strong>Unusual quantity from OUT031</strong><p>ORD0096815: 210 chilled units — 1.6× the outlet’s usual order.</p></div><div className="inline-actions"><ActionButton kind="secondary">Message store</ActionButton><ActionButton kind="ghost">Resolve with note</ActionButton></div></div></div></OperationsShell>;
}

export function DispatcherIssue() {
  return <OperationsShell role="Dispatcher" active="attention" badge="Queue closed"><PageHeading backTo="/dispatcher/dp09" backLabel="Needs Attention" title="ISS-0417 · 2 cartons of Cream crackers short" subtitle="OUT010 · ORD0096653 · Dry · delivered Tue 24 Mar" /><div className="issue-resolve-layout"><div><Card><h2>Case progress</h2><Timeline items={[["Reported",'15:45 · by the store on receipt','done'],["Acknowledged",'16:06 · by you','done'],["Under review",'Compare the evidence below','current'],["Resolved",'The store can confirm or reopen once','todo']]} /></Card><Card><div className="section-title-row"><h2>Evidence compared</h2><StatusChip tone="success">Verified: loading stage</StatusChip></div><div className="data-table evidence-table"><div className="table-head"><span>Stage</span><span>Count</span><span>Evidence</span></div><div className="table-row"><strong>Loader · 03:58</strong><span>42 of 44</span><span>FR-D08 Cream crackers flagged 2 short</span></div><div className="table-row"><strong>Driver · 04:44</strong><span>42 delivered</span><span>Proof photo and receiver name</span></div><div className="table-row"><strong>Store · 15:45</strong><span>42 of 44</span><span>Note: matches the loader’s flag</span></div></div></Card></div><Card><h2>Resolve the case</h2><div className="radio-stack"><RadioCard title="Credit 2 cartons to OUT010" description="The outlet’s account is credited for 2 × FR-D08." checked /><RadioCard title="Send a replacement today" description="Needs a spare vehicle and loader time." /><RadioCard title="Not verified — close without action" description="Use when the evidence doesn’t support the report." /></div><label className="field-label">Resolution note (required)<textarea defaultValue="Loader count confirms FR-D08 was short at loading. 2 cartons credited to OUT010’s account." /></label><ActionLink className="full" to="/dispatcher/dp11">Resolve case</ActionLink><p className="helper">Only verified, stage-attributed cases affect performance records.</p></Card></div></OperationsShell>;
}

export function CaseResolved() {
  return <OperationsShell role="Dispatcher" active="attention" badge="Queue closed"><div className="center-result"><ResultCard title="Case resolved" description="OUT010’s store manager has been notified and can confirm the outcome or reopen the case once."><KeyRows rows={[["Case",'ISS-0417'],["Resolved",'Tue 24 Mar 2026 · 16:08'],["Outcome",'Credit for 2 cartons (outlet account)'],["Attributed to",'Loading stage (verified)'],["Status",<StatusChip tone="success">Resolved</StatusChip>]]}/><div className="inline-actions"><ActionLink to="/dispatcher/dp09">Back to Needs Attention</ActionLink><ActionLink kind="secondary" to="/dispatcher/dp01">Go to order queue</ActionLink></div></ResultCard></div></OperationsShell>;
}

const deferrals = [['ORD0096862','OUT075','Wed 25 Mar','Thu 26 Mar','Other — trip-time budget','First deferral'],['ORD0096518','OUT010','Mon 23 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096654','OUT010','Tue 24 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096515','OUT008','Mon 23 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096650','OUT008','Tue 24 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096520','OUT011','Mon 23 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096656','OUT011','Tue 24 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096522','OUT012','Mon 23 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096658','OUT012','Tue 24 Mar','Wed 25 Mar','Chilled vehicle capacity','2 in a row'],['ORD0096647','OUT006','Tue 24 Mar','Wed 25 Mar','Chilled vehicle capacity','Deferred once']];
export function DeferralLog() {
  return <OperationsShell role="Dispatcher" active="deferrals" badge="Published v1"><PageHeading title="Deferral Log" subtitle="Peliyagoda · every deferral with its reason and new date" /><div className="search-actions"><label><Search/><input placeholder="Order, outlet or reason" /></label><div className="filter-row"><button className="active">All</button><button>Consecutive</button><button>Chilled</button><button>Last 7 days</button></div><ActionButton kind="secondary">Export CSV</ActionButton></div><Card className="table-card"><div className="data-table deferral-table"><div className="table-head"><span>Order</span><span>Outlet</span><span>Type</span><span>Ordered</span><span>Delivered on</span><span>Reason</span><span>Flag</span></div>{deferrals.map(row=><div className="table-row" key={row[0]}><span>{row[0]}</span><span>{row[1]}</span><span>Chilled</span>{row.slice(2,5).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[5].includes('2') ? 'danger' : 'warning'}>{row[5]}</StatusChip></div>)}</div></Card></OperationsShell>;
}

const weeks = [['W14','30 Mar','—','52','54','OK'],['W15','6 Apr','New Year build-up','58','54','Short 4'],['W16','13 Apr','New Year · 4 days','37','36','Short 1'],['W17','20 Apr','—','52','54','OK'],['W18','27 Apr','Vesak · 5 days','44','45','OK'],['W19','4 May','—','53','54','OK'],['W20','11 May','—','51','54','OK'],['W21','18 May','Poson build-up','55','54','Short 1'],['W22','25 May','Poson','52','54','OK'],['W23','1 Jun','—','52','54','OK']];
export function CapacityForecast() {
  return <OperationsShell role="Dispatcher" active="forecast" badge="Published v1"><PageHeading title="Capacity Forecast" subtitle="Peliyagoda · reefer trips needed vs available · weeks 14–23, 2026" /><div className="filter-row"><button className="active">Reefer trips (chilled)</button><button>Ambient trips</button><button>Tonnage by brand</button></div><div className="info-banner"><Info/><div><strong>Forecast values are sample model output</strong><p>Built from the same weeks last year, adjusted by this year’s trend.</p></div></div><Card className="forecast-chart"><h2>Reefer trips per week</h2><div className="bars">{weeks.map(([week,date,,need,capacity,status])=><div className="bar-group" key={week}><span>{need}</span><i className={status==='OK'?'':'over'} style={{height:`${Number(need)*2.5}px`}}/><b style={{bottom:`${Number(capacity)*2.5}px`}}/><strong>{week}</strong><small>{date}</small></div>)}</div></Card><div className="forecast-bottom"><Card><h2>Week by week</h2><div className="data-table week-table"><div className="table-head"><span>Week</span><span>Starts</span><span>Calendar</span><span>Need</span><span>Capacity</span><span>Gap</span></div>{weeks.map(row=><div className="table-row" key={row[0]}>{row.slice(0,5).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[5]==='OK'?'success':'danger'}>{row[5]}</StatusChip></div>)}</div></Card><Card><h2>Recommendation</h2><strong>Add 1 reefer truck for weeks 15, 16 and 21</strong><p>Reefer demand is forecast to exceed capacity by 1–4 trips in those weeks.</p><StatusChip>What-if: +1 reefer truck</StatusChip></Card></div></OperationsShell>;
}

const vehicleData = [['VEH001','Truck · reefer','5,510','26.4','4.7','340','Available'],['VEH002','Truck · reefer','3,990','21.1','6.1','610','Available'],['VEH003','Truck · reefer','5,510','26.4','4.7','480','Available'],['VEH005','Truck · reefer','6,840','33.4','4.4','490','Available'],['VEH006','Truck · reefer','6,840','33.4','4.4','380','Available'],['VEH007','Truck · reefer','3,610','19.4','6.4','590','Available'],['VEH008','Truck · ambient','3,800','22.0','7.1','460','Available'],['VEH009','Truck · ambient','5,800','30.0','5.2','440','Available'],['VEH012','Truck · ambient','4,200','24.0','6.8','540','Available'],['VEH025','Truck · ambient','3,800','22.0','7.1','580','In workshop'],['VEH036','Van · reefer','1,040','7.0','10.3','480','Available'],['VEH038','Van · ambient','1,200','9.0','10.8','620','Available']];
export function ReferenceData() {
  return <OperationsShell role="Dispatcher" active="reference" badge="Published v2"><PageHeading title="Reference Data" subtitle="Peliyagoda master data: outlets, vehicles, operating calendar and workshop status" /><div className="filter-row"><button className="active">Vehicles</button><button>Outlets</button><button>Operating calendar</button></div><div className="info-banner"><Info/><div><strong>Master data is read-only here</strong><p>Identifiers and limits come from shared master data. Dispatchers can only change a vehicle’s workshop status.</p></div></div><Card className="table-card"><div className="data-table reference-table"><div className="table-head"><span>Vehicle</span><span>Type</span><span>Max kg</span><span>Max m³</span><span>km / L</span><span>Fuel quota L/wk</span><span>Workshop status</span><span/></div>{vehicleData.map(row=><div className="table-row" key={row[0]}>{row.slice(0,6).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[6]==='Available'?'success':'danger'}>{row[6]}</StatusChip><button>Change</button></div>)}</div><p className="table-note">Showing 12 of 38 Peliyagoda vehicles. Values from vehicles.csv.</p></Card></OperationsShell>;
}
