import { AlertTriangle, Camera, Check, CheckCircle2, CircleAlert, Info, Package } from 'lucide-react';
import { ActionButton, ActionLink, Card, IconBubble, KeyRows, ModalPage, OperationsShell, PageHeading, Quantity, RadioCard, ResultCard, StatusChip } from './ui';

const trips = [['02:00','VEH007','Trip 1 · Puttalam','1','Chilled','Loaded'],['02:00','VEH008','Trip 1 · Puttalam','3','Ambient','Loaded'],['02:38','VEH016','Trip 1 · Kurunegala','4','Ambient','Loaded'],['02:57','VEH015','Trip 1 · Matara','4','Ambient','Loaded'],['03:09','VEH018','Trip 1 · Galle','6','Ambient','Loaded'],['03:23','VEH031','Trip 1 · Galle','6','Chilled','Loaded'],['03:53','VEH009','Trip 1 · Kalutara (was VEH025)','7','Ambient','Plan changed'],['04:08','VEH012','Trip 1 · Colombo','5','Ambient','Not started'],['04:14','VEH005','Trip 1 · Colombo','7','Chilled · reefer check','Not started'],['04:16','VEH031','Trip 1 · Kalutara','3','Chilled · reefer check','Not started']];

const loadStops = [['Load 1st','Stop 5','OUT014'],['Load 2nd','Stop 4','OUT011'],['Load 3rd','Stop 3','OUT009'],['Load 4th','Stop 2','OUT010'],['Load 5th','Stop 1','OUT008']];
const productNames = ['Wheat flour','Ceylon black tea','Instant noodles','Cream crackers','Laundry soap bar','Toilet tissue'];

function LoaderStats() { return <div className="queue-stats">{[['22','Trips today','Peliyagoda'],['5','Loaded','Ready to drivers'],['1','Loading','VEH012'],['1','Plan changed','Needs re-verification'],['15','Not started','Next: VEH012 at 04:08']].map(([v,l,d])=><Card key={l}><strong>{v}</strong><span>{l}</span><small>{d}</small></Card>)}</div>; }

export function TripQueue() {
  return <OperationsShell role="Loader" active="queue"><PageHeading title="Trip queue" subtitle="Wed 25 Mar 2026 · plan v2 · earliest departures first" /><div className="danger-banner"><CircleAlert/><div><strong>Plan changed at 03:08 · Kalutara trip</strong><p>VEH025 is out of service. The trip moves to VEH009 — check what you’ve already loaded.</p></div><ActionLink to="/loader/ld08">View change</ActionLink></div><LoaderStats/><Card className="table-card"><div className="data-table trip-table"><div className="table-head"><span>Departs</span><span>Vehicle</span><span>Trip</span><span>Stops</span><span>Temperature</span><span>Status</span><span/></div>{trips.map(row=><div className="table-row" key={`${row[0]}${row[1]}`}>{row.slice(0,5).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[5]==='Loaded'?'success':row[5]==='Plan changed'?'danger':'neutral'}>{row[5]}</StatusChip>{row[5]!=='Loaded'?<ActionLink kind="secondary" to={row[1]==='VEH009'?'/loader/ld08':row[1]==='VEH005'?'/loader/ld06':'/loader/ld02'}>Open</ActionLink>:<span/>}</div>)}</div><p className="table-note">Showing 10 of 22 trips · 12 more depart between 04:38 and 05:54</p></Card></OperationsShell>;
}

function BeforeLoad({ chilled = false }: { chilled?: boolean }) {
  return <OperationsShell role="Loader" active="active"><PageHeading backTo="/loader/ld01" backLabel="Trip queue" title={`Before you load · ${chilled?'VEH005':'VEH012'}`} subtitle={`Trip 1 · Colombo · ${chilled?'chilled':'ambient'} · departs ${chilled?'04:14':'04:08'}`} /><div className="before-layout"><div><Card><h2>1 · Reefer at temperature <StatusChip tone={chilled?'warning':'neutral'}>{chilled?'Required':'Not needed'}</StatusChip></h2>{chilled?<><p>Check the reefer unit display before loading chilled goods. Loading can’t start until this is confirmed.</p><div className="reefer-check"><label className="field-label">Unit reading (°C)<input defaultValue="4" /></label><label><input type="checkbox" /> Reefer is at temperature</label></div></>:<p>Ambient trip — no chilled goods on this vehicle.</p>}</Card><Card><h2>2 · Confirm the loading order <StatusChip tone="warning">Required</StatusChip></h2><p>Load in reverse delivery order. The last stop goes in first, the first stop goes nearest the doors.</p><div className="loading-order">{(chilled?[...loadStops,['Load 6th','Stop 2','OUT013'],['Load 7th','Stop 1','OUT010']]:loadStops).map(([load,stop,outlet],i)=><div key={outlet}><span>{i+1}</span><strong>{load} · {stop} · {outlet}</strong></div>)}</div><label className="check-confirm"><input type="checkbox" defaultChecked={!chilled}/> I’ve checked the loading order — last stop loads first</label></Card><div className="inline-actions"><ActionLink to="/loader/ld03">Start loading</ActionLink>{chilled&&<ActionLink kind="secondary" to="/loader/ld01">Back to trip queue</ActionLink>}</div></div><Card className="summary-card"><h2>{chilled?'VEH005':'VEH012'} · Trip 1</h2><KeyRows rows={[["Vehicle",chilled?'VEH005 · reefer truck':'VEH012 · ambient truck'],["Departs",chilled?'04:14':'04:08'],["Area",chilled?'Colombo · Fresh chilled':'Colombo · Fresh dry'],["Stops",chilled?'7':'5'],["Load",chilled?'1,068.8 kg · 16.33 m³':'216 units · 1,605.4 kg · 8.608 m³']]} /></Card></div></OperationsShell>;
}
export const BeforeAmbient = () => <BeforeLoad/>;
export const BeforeChilled = () => <BeforeLoad chilled/>;

function Checklist({ offline = false }: { offline?: boolean }) {
  return <OperationsShell role="Loader" active="active" badge={offline?'Offline · saving local':'Online'}><PageHeading title="Loading VEH012 · Trip 1" subtitle="Tick each line as it goes on the truck. Flag anything missing or damaged — it won’t block departure." />{offline&&<div className="warning-banner"><AlertTriangle/><div><strong>Connection lost at 03:26 — your ticks are saved on this terminal</strong><p>2 ticks are waiting to sync. Keep loading; they’ll send when the connection returns.</p></div></div>}<div className="checklist-layout"><div><Card className="progress-card"><h2>Progress</h2><div className="load-progress"><span><i style={{width:'58%'}}/></span><strong>{offline?'16':'14'} / 29 lines</strong></div><small>Loading order confirmed at 03:16 · last stop first</small></Card>{loadStops.map(([load,stop,outlet],stopIndex)=><section className="load-stop" key={outlet}><header><div><strong>{load} · {stop} · {outlet}</strong><small>ORD00967{97-stopIndex} · 40 units</small></div><StatusChip tone={stopIndex<2?'success':'neutral'}>{stopIndex<2?'5 / 5':'0 / 8'}</StatusChip></header>{productNames.slice(0,stopIndex===0?5:stopIndex===1?6:4).map((name,index)=><div className="checklist-row" key={name}><label><input type="checkbox" defaultChecked={stopIndex<2||index<2}/><span/></label><strong>{name}</strong><small>FR-D0{index+1} · 10 × 1 kg pack</small><b>Qty {index+3}</b><ActionLink kind="ghost" to="/loader/ld-o1">Flag</ActionLink></div>)}</section>)}</div><Card className="summary-card"><h2>VEH012 · Trip 1</h2><KeyRows rows={[["Departs",'04:08'],["Area",'Colombo · Fresh dry'],["Stops",'5'],["Load",'216 units · 1,605.4 kg · 8.608 m³']]} /><ActionLink className="full" to="/loader/ld04">{offline?'Retry sync':'Review and confirm'}</ActionLink><p className="helper">You can correct ticks and flags until you confirm the trip.</p></Card></div></OperationsShell>;
}
export const LoadingChecklist = () => <Checklist/>;
export const ConnectionDrop = () => <Checklist offline/>;

export function FlagProblemDialog() {
  return <ModalPage title="Flag a problem" description="Instant noodles · FR-D07 · 12 × 5-pack"><p>OUT010 · ORD0096797 · planned quantity 9</p><div className="radio-stack"><RadioCard title="Missing" description="Not found at the dock or short in the pick."/><RadioCard title="Damaged" description="Arrived at the dock damaged; not loaded." checked/></div><div className="flag-quantity"><span>Quantity affected</span><Quantity value={1}/></div><label className="field-label">Note (optional)<input defaultValue="Outer carton crushed; packs inside are wet."/></label><div className="photo-row"><button><Camera/>Photo attached</button><p>Optional. The Dispatcher and OUT010 see this flag before the truck arrives.</p></div><div className="modal-actions"><ActionLink kind="secondary" to="/loader/ld03">Cancel</ActionLink><ActionLink to="/loader/ld04">Save flag</ActionLink></div></ModalPage>;
}

const summaryStops = [['1st','5','OUT014','ORD0096804','8 / 8','All loaded'],['2nd','4','OUT011','ORD0096799','5 / 5','All loaded'],['3rd','3','OUT009','ORD0096796','6 / 6','All loaded'],['4th','2','OUT010','ORD0096797','8 / 9','1 damaged'],['5th','1','OUT008','ORD0096793','5 / 5','All loaded']];
export function LoadSummary() {
  return <OperationsShell role="Loader" active="active"><PageHeading backTo="/loader/ld03" backLabel="Back to checklist" title="Confirm VEH012 is loaded" subtitle="Check the summary. Flags are shared with the Dispatcher and the store before the truck leaves." /><div className="warning-banner"><AlertTriangle/><div><strong>Instant noodles (FR-D07) · OUT010 · 1 carton damaged</strong><p>Loaded 8 of 9. Note and photo attached. OUT010 will see this as an expected shortfall.</p></div></div><div className="two-column"><Card><h2>By stop, in loading order</h2><div className="data-table load-summary-table"><div className="table-head"><span>Loaded</span><span>Stop</span><span>Outlet</span><span>Order</span><span>Lines</span><span>Status</span></div>{summaryStops.map(row=><div className="table-row" key={row[2]}>{row.slice(0,5).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[5]==='All loaded'?'success':'warning'}>{row[5]}</StatusChip></div>)}</div></Card><Card className="summary-card"><h2>Totals</h2><KeyRows rows={[["Lines",'29 · 28 ticked, 1 flagged'],["Units loaded",'215 of 216'],["Loading order",'Confirmed 03:18'],["Flags",'1 · damaged']]} /><ActionLink className="full" to="/loader/ld05">Confirm trip loaded</ActionLink><ActionLink className="full" kind="secondary" to="/loader/ld03">Back to checklist</ActionLink></Card></div></OperationsShell>;
}

function LoadedResult({ moved = false }: { moved?: boolean }) {
  return <OperationsShell role="Loader" active={moved?'queue':'active'}><div className="center-result"><ResultCard title={`${moved?'VEH009':'VEH012'} is loaded`} description={moved?'Plan v2 is verified. The reassigned driver can now see the Kalutara trip.':'The driver can now see this trip. The flag has gone to the Dispatcher and OUT010.'}><KeyRows rows={moved?[["Trip",'VEH009 · Trip 1 · Kalutara'],["Confirmed",'Wed 25 Mar 2026 · 03:44 · by you'],["Moved from VEH025",'3 stops'],["Flags",'None'],["Status",<StatusChip tone="success">Loaded</StatusChip>]]:[["Trip",'VEH012 · Trip 1 · Colombo'],["Confirmed",'Wed 25 Mar 2026 · 03:52 · by you'],["Units",'215 of 216'],["Flags",'1 · Instant noodles damaged (OUT010)'],["Status",<StatusChip tone="success">Loaded</StatusChip>]]}/><ActionLink to="/loader/ld01">Back to trip queue</ActionLink></ResultCard></div></OperationsShell>;
}
export const Loaded = () => <LoadedResult/>;
export const ReassignedLoaded = () => <LoadedResult moved/>;

export function PlanChanged() {
  return <OperationsShell role="Loader" active="queue"><PageHeading backTo="/loader/ld01" backLabel="Trip queue" title="Plan changed · Kalutara trip" subtitle="Plan v2 published by the Dispatcher at 03:08" /><div className="danger-banner"><CircleAlert/><div><strong>VEH025 is out of service — this trip moves to VEH009</strong><p>Move the stops you’ve already loaded, then load the rest straight onto VEH009. Departure stays at 03:53.</p></div></div><div className="compare-grid"><Card><h2>Before · plan v1</h2><KeyRows rows={[["Vehicle",'VEH025 · ambient truck'],["Capacity",'3,800 kg · 22 m³'],["Stops",'7 · Kalutara'],["Departs",'03:53'],["Status",'Out of service']]} /></Card><Card className="selected-compare"><h2>Now · plan v2</h2><KeyRows rows={[["Vehicle",'VEH009 · ambient truck'],["Capacity",'5,800 kg · 30 m³'],["Stops",'7 · Kalutara · same order'],["Departs",'03:53'],["Status",'Ready at the dock']]} /></Card></div><Card><h2>What to do</h2><div className="data-table move-table"><div className="table-head"><span>Load order</span><span>Stop</span><span>Outlet</span><span>Order</span><span>Units</span><span>Action</span></div>{[['1st','7','OUT045','ORD0096832','33','Loaded on VEH025 → move'],['2nd','6','OUT044','ORD0096831','45','Loaded on VEH025 → move'],['3rd','5','OUT042','ORD0096828','115','Loaded on VEH025 → move'],['4th','4','OUT040','ORD0096824','103','Not loaded → load on VEH009'],['5th','3','OUT046','ORD0096833','35','Not loaded → load on VEH009'],['6th','2','OUT043','ORD0096830','34','Not loaded → load on VEH009'],['7th','1','OUT041','ORD0096826','52','Not loaded → load on VEH009']].map(row=><div className="table-row" key={row[2]}>{row.slice(0,5).map(x=><span key={x}>{x}</span>)}<StatusChip tone={row[5].includes('move')?'warning':'neutral'}>{row[5]}</StatusChip></div>)}</div></Card><div className="inline-actions publish-actions"><ActionLink to="/loader/ld09">Acknowledge and re-verify</ActionLink><span className="helper">Your acknowledgement is recorded in the audit trail.</span></div></OperationsShell>;
}

export function Reverify() {
  return <OperationsShell role="Loader" active="active"><PageHeading title="Re-verify VEH009 · Kalutara" subtitle="Confirm each stop is on VEH009 in loading order" /><Card className="reverify-list">{[['1st','7','OUT045','ORD0096832 · 33 units','Moved from VEH025'],['2nd','6','OUT044','ORD0096831 · 45 units','Moved from VEH025'],['3rd','5','OUT042','ORD0096828 · 115 units','Moved from VEH025'],['4th','4','OUT040','ORD0096824 · 103 units','Loaded on VEH009'],['5th','3','OUT046','ORD0096833 · 35 units','Loaded on VEH009'],['6th','2','OUT043','ORD0096830 · 34 units','Loaded on VEH009'],['7th','1','OUT041','ORD0096826 · 52 units','Loaded on VEH009']].map(([load,stop,outlet,order,status])=><div key={outlet}><Check/><strong>Load {load} · Stop {stop} · {outlet}</strong><span>{order}</span><StatusChip tone={status.includes('Moved')?'warning':'success'}>{status}</StatusChip></div>)}</Card><div className="reverify-actions"><ActionLink to="/loader/ld10">Confirm VEH009 loaded</ActionLink><span className="load-progress"><span><i style={{width:'100%'}}/></span><strong>7 / 7 stops</strong></span></div></OperationsShell>;
}

export function LoadingIssues() {
  return <OperationsShell role="Loader" active="issues"><PageHeading title="Loading issues" subtitle="Missing or damaged items flagged at the dock, and what happened next" /><div className="filter-row"><button className="active">This shift</button><button>Yesterday</button><button>All</button></div><Card className="table-card"><div className="data-table loading-issues-table"><div className="table-head"><span>Flagged</span><span>Vehicle</span><span>Outlet · order</span><span>Product</span><span>Problem</span><span>Status</span></div><div className="table-row"><strong>Wed 25 Mar · 03:47</strong><span>VEH012</span><span>OUT010 · ORD0096797</span><span>Instant noodles · FR-D07</span><span>Damaged · 1</span><StatusChip tone="warning">Reported</StatusChip></div><div className="table-row"><strong>Tue 24 Mar · 03:58</strong><span>VEH022</span><span>OUT010 · ORD0096653</span><span>Cream crackers · FR-D08</span><span>Missing · 2</span><StatusChip tone="success">Resolved · ISS-0417</StatusChip></div></div><p className="table-note">Statuses follow the shared issue lifecycle: Reported → Acknowledged → Under review → Resolved.</p></Card></OperationsShell>;
}
