import { useState } from 'react';
import { Link } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, ArrowUpRight, RefreshCw, Settings2 } from 'lucide-react';
import { Alert, Badge, Button, CapacityBar, Card, CardContent, CardHeader, Checkbox, Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger, EmptyState, FilterBar, FormField, Input, PageHeader, Pagination, Radio, SearchInput, Select, Sheet, SheetContent, SheetDescription, SheetTitle, SheetTrigger, Skeleton, StepIndicator, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs, TabsContent, TabsList, TabsTrigger, Textarea, Timeline, Tooltip, TooltipContent, TooltipTrigger, toast } from '@waypoint/ui';
import { fetchHealth, fetchReadiness } from '../lib/api';
import { workspaces } from '../app/workspaces';

const demoSchema = z.object({ label: z.string().trim().min(2, 'Enter at least two characters.') });
type DemoForm = z.infer<typeof demoSchema>;
function FormDemo() {
  const { register, handleSubmit, formState: { errors } } = useForm<DemoForm>({ resolver: zodResolver(demoSchema), defaultValues: { label: '' } });
  return <form className="foundation-demo" onSubmit={handleSubmit(() => toast.success('Component demo validated. Nothing was stored.'))} noValidate><FormField id="demo-label" label="Example label" description="Component demonstration only. Nothing is saved." error={errors.label?.message} required><Input id="demo-label" placeholder="Try a label" aria-invalid={Boolean(errors.label)} aria-describedby={`demo-label-description${errors.label ? ' demo-label-error' : ''}`} {...register('label')} /></FormField><Button type="submit">Validate example</Button></form>;
}
export default function FoundationPage() {
  const [page, setPage] = useState(1);
  const health = useQuery({ queryKey: ['health'], queryFn: ({ signal }) => fetchHealth(signal) });
  const database = useQuery({ queryKey: ['readiness'], queryFn: ({ signal }) => fetchReadiness(signal) });
  return <main className="foundation-page"><div className="foundation-top"><Button asChild variant="ghost"><Link to="/dispatcher"><ArrowLeft size={16} aria-hidden="true" />Back to workspace</Link></Button><Badge tone="info">Development foundation</Badge></div><PageHeader eyebrow="PHASE 2 / SYSTEM FOUNDATION" title="A shared foundation." description="Real service checks, reusable components and four workspace previews. Sample component values below are not operational data." /><div className="foundation-grid">
    <Card><CardHeader><h2>Service connectivity</h2><p className="component-note">These checks call the running API from your browser.</p></CardHeader><CardContent><div className="service-row"><div><strong>API liveness</strong><p>GET /api/v1/health</p></div><Badge tone={health.isError ? 'critical' : health.isSuccess ? 'success' : 'neutral'}>{health.isPending ? 'Checking API' : health.isError ? 'API unavailable' : 'API connected'}</Badge></div><div className="service-row"><div><strong>Database readiness</strong><p>Prisma → PostgreSQL</p></div><Badge tone={database.isError ? 'critical' : database.isSuccess ? 'success' : 'neutral'}>{database.isPending ? 'Checking database' : database.isError ? 'Database unavailable' : 'Database connected'}</Badge></div>{(health.isError || database.isError) && <Alert title="A service could not be reached" tone="warning">Check the API and database processes, then retry. A browser connection does not guarantee service availability.</Alert>}<div className="mt-5"><Button variant="secondary" loading={health.isFetching || database.isFetching} onClick={() => { void health.refetch(); void database.refetch(); }}><RefreshCw size={15} aria-hidden="true" />Check again</Button></div></CardContent></Card>
    <Card><CardHeader><h2>Workspace previews</h2><p className="component-note">Navigation previews, not authenticated roles.</p></CardHeader><CardContent><div className="foundation-demo">{workspaces.map(({ id, name, icon: Icon }) => <Button key={id} asChild variant="secondary"><Link to={`/${id}`}><Icon size={18} aria-hidden="true" />{name}<ArrowUpRight size={15} aria-hidden="true" /></Link></Button>)}</div></CardContent></Card>
    <Card><CardHeader><h2>Actions and feedback</h2></CardHeader><CardContent className="foundation-demo"><div className="demo-row"><Button onClick={() => toast.success('Example notification. No business action was performed.')}>Show notification</Button><Button variant="secondary">Secondary</Button><Button disabled>Unavailable</Button><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" aria-label="About this example"><Settings2 size={18} /></Button></TooltipTrigger><TooltipContent>Reusable interface primitives</TooltipContent></Tooltip></div><div className="demo-row"><Badge>Neutral</Badge><Badge tone="info">Information</Badge><Badge tone="success">Success</Badge><Badge tone="warning">Attention</Badge><Badge tone="critical">Critical</Badge></div><Alert title="Explicit interface states">Color supports the label; it never replaces the meaning.</Alert><div className="demo-row"><Dialog><DialogTrigger asChild><Button variant="secondary">Open dialog</Button></DialogTrigger><DialogContent><DialogTitle>Example dialog</DialogTitle><DialogDescription>This is an accessible component demonstration. Focus returns to the trigger when closed.</DialogDescription></DialogContent></Dialog><Sheet><SheetTrigger asChild><Button variant="secondary">Open sheet</Button></SheetTrigger><SheetContent><SheetTitle>Example sheet</SheetTitle><SheetDescription>A reusable detail surface. No domain data is loaded.</SheetDescription></SheetContent></Sheet></div></CardContent></Card>
    <Card><CardHeader><h2>Forms and validation</h2></CardHeader><CardContent className="foundation-demo"><FormDemo /><FormField id="demo-select" label="Select example"><Select id="demo-select" defaultValue="one"><option value="one">First option</option><option value="two">Second option</option></Select></FormField><FormField id="demo-note" label="Textarea example"><Textarea id="demo-note" placeholder="Component example — not saved" /></FormField><label className="demo-check"><Checkbox />Checkbox example</label><fieldset><legend className="component-note">Radio example</legend><div className="demo-row"><label className="demo-check"><Radio name="demo-radio" value="one" defaultChecked />One</label><label className="demo-check"><Radio name="demo-radio" value="two" />Two</label></div></fieldset></CardContent></Card>
    <Card><CardHeader><h2>Lists and navigation</h2></CardHeader><CardContent className="foundation-demo"><FilterBar aria-label="Example filters"><SearchInput label="Search component example" placeholder="Example search input" /></FilterBar><Tabs defaultValue="table"><TabsList aria-label="Example presentation"><TabsTrigger value="table">Table</TabsTrigger><TabsTrigger value="empty">Empty state</TabsTrigger></TabsList><TabsContent value="table"><Table><caption className="sr-only">Component examples, not operational records</caption><TableHead><TableRow><TableHeader>Component</TableHeader><TableHeader>Purpose</TableHeader></TableRow></TableHead><TableBody><TableRow><TableCell>Table</TableCell><TableCell>Structured information</TableCell></TableRow><TableRow><TableCell>Card</TableCell><TableCell>Grouped context</TableCell></TableRow></TableBody></Table></TabsContent><TabsContent value="empty"><EmptyState title="No example records" description="A clear next step belongs beside a genuine empty state." /></TabsContent></Tabs><Pagination page={page} pageCount={3} onPageChange={setPage} /><p className="component-note">Pagination controls are isolated examples, not a connected data list.</p></CardContent></Card>
    <Card><CardHeader><h2>Progress primitives</h2><p className="component-note">Illustrative values for component review only.</p></CardHeader><CardContent className="foundation-demo"><CapacityBar label="Example capacity" value={4} maximum={10} unit="units" /><StepIndicator steps={['Structure', 'Review', 'Extend']} current={1} /><Timeline label="Component example" items={[{ id: 'one', title: 'A recorded event', description: 'Timestamp and provenance belong with the event.' }, { id: 'two', title: 'A following event', description: 'No delivery workflow is active.' }]} /><div aria-label="Loading skeleton example"><Skeleton className="h-5 w-40 mb-3" /><Skeleton className="h-16 w-full" /></div></CardContent></Card>
  </div></main>;
}
